version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - nlreturn
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
