version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...
    ## This creates MANUAL and MANUAL.html. The gzip then makes MANUAL.gz (a man page).
    - go run github.com/davidnewhall/md2roff@v0.0.1 --manual xt --version "{{.Version}}" --date "{{.Date}}" MANUAL.md
    - rm -f MANUAL.gz
    - gzip -9 MANUAL

builds:
  - env:
      - CGO_ENABLED=0
      - CGO_LDFLAGS=-mmacosx-version-min=10.8
      - CGO_CFLAGS=-mmacosx-version-min=10.8
    goos:
      - linux
      - windows
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - '386'
    ldflags:
      - -s -w
      - -X "golift.io/version.Version={{.Version}}"
      - -X "golift.io/version.BuildDate={{.Date}}"
      - -X "golift.io/version.BuildUser={{.Env.USER}}"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: '386'

universal_binaries:
  - replace: true

archives:
  - format: tar.gz
    wrap_in_directory: true
    files:
     - src: MANUAL.html
       dst: xt-manual.html
     - src: LICENSE
       dst: LICENSE.txt
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: xt-packages
    vendor: Go Lift
    homepage: https://unpackerr.com
    maintainer: David Newhall II <captain at golift dot io>
    description: eXtractor Tool - Recursively decompress archives
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
      - apk
    bindir: /usr/bin
    version_metadata: git
    section: default
    priority: extra
    provides:
      - xt
    # signing
    rpm:
      signature:
        key_file: "{{ .Env.GPG_SIGNING_KEY }}"
    deb:
      signature:
        key_file: "{{ .Env.GPG_SIGNING_KEY }}"
        type: origin
    contents:
      - src: MANUAL.gz
        dst: /usr/share/man/man1/xt.1.gz
      - src: LICENSE
        dst: /usr/share/doc/xt/LICENSE.txt
      - src: MANUAL.md
        dst: /usr/share/doc/xt/MANUAL.md

signs:
    - artifacts: all

brews:
  - name: xt
    # enable the line below only for testing locally
    #skip_upload: true
    repository:
      owner: golift
      name: homebrew-mugs
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: https://unpackerr.com/
    description: "eXtractor Tool - Recursively decompress archives"
    license: MIT
    url_template: "https://github.com/Unpackerr/xt/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    test: assert_match "xt v#{version}", shell_output("#{bin}/xt -v 2>&1", 2)
    install: bin.install "xt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
